### ISSUE TITLE
Components Fluig Com Código Aberto

### ISSUE THREAD

**Issue by brunocroh** [fluig/Compartilhe-seu-projeto#10]
Os componentes JQuery do fluig poderiam ter seu código fonte disponibilizado aqui no github, assim qualquer desenvolvedor fluig poderia corrigir problemas existentes nos componentes ou até mesmo adicionar novos componentes ao projeto

Os artefatos que que refiro são :
- fluig-style-guide.min.js
- fluig-style-guide.min.css

@fluigDev 
@peter-angelo 
@jose-fluig

**Comment by Eliezergimenes** [comment]
Seria ótimo!

**Comment by BrunoMarc** [comment]
Apoio tbm haha

**Comment by peter-angelo** [comment]
Vamos avaliar com carinho a sugestão. Logo mais te damos uma resposta Bruno.

**Comment by Brunocroh** [comment]
@peter-angelo Obrigado, estou aguardando ansiosamente

**Comment by peter-angelo** [comment]
Olá Bruno, conversei com o Product Owner e líder do respectivo card do fluig sobre este assunto. A definição é que faz sentido compartilhar isto abertamente no GitHub, porém ainda não é o momento, devido as mudanças que estão sendo feitas neste exato momento. A próxima release do fluig terá grandes mudanças e que podem afetar diretamente estes arquivos ou o core da plataforma.

De qualquer forma, vou manter este assunto no radar para viabilizar em um futuro próximo.

**Comment by Thiago332** [comment]
Olá, Prezados

@peter, falta material disponibilizado pela própria TOTVS aqui!!

1)acelaradores

2)templates

3)Datasets


Abs,

**Comment by lrphael** [comment]
@peter-angelo alguma novidades sobre a disponibilização desses arquivos?
